/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as RealisationsRouteImport } from './routes/realisations'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAtoutsRouteImport } from './routes/_authenticated/admin.atouts'
import { Route as AuthenticatedAdminComparaisonRouteImport } from './routes/_authenticated/admin.comparaison'
import { Route as AuthenticatedAdminEtapesRouteImport } from './routes/_authenticated/admin.etapes'
import { Route as AuthenticatedAdminFaqRouteImport } from './routes/_authenticated/admin.faq'
import { Route as AuthenticatedAdminMediasRouteImport } from './routes/_authenticated/admin.medias'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin.messages'
import { Route as AuthenticatedAdminRealisationsRouteImport } from './routes/_authenticated/admin.realisations'
import { Route as AuthenticatedAdminSectionsRouteImport } from './routes/_authenticated/admin.sections'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin.services'
import { Route as AuthenticatedAdminTarifsRouteImport } from './routes/_authenticated/admin.tarifs'
import { Route as AuthenticatedAdminTemoignagesRouteImport } from './routes/_authenticated/admin.temoignages'
import { Route as AuthenticatedAdminTextesRouteImport } from './routes/_authenticated/admin.textes'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RealisationsRoute = RealisationsRouteImport.update({
  id: '/realisations',
  path: '/realisations',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAtoutsRoute =
  AuthenticatedAdminAtoutsRouteImport.update({
    id: '/atouts',
    path: '/atouts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminComparaisonRoute =
  AuthenticatedAdminComparaisonRouteImport.update({
    id: '/comparaison',
    path: '/comparaison',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEtapesRoute =
  AuthenticatedAdminEtapesRouteImport.update({
    id: '/etapes',
    path: '/etapes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFaqRoute = AuthenticatedAdminFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMediasRoute =
  AuthenticatedAdminMediasRouteImport.update({
    id: '/medias',
    path: '/medias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRealisationsRoute =
  AuthenticatedAdminRealisationsRouteImport.update({
    id: '/realisations',
    path: '/realisations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSectionsRoute =
  AuthenticatedAdminSectionsRouteImport.update({
    id: '/sections',
    path: '/sections',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTarifsRoute =
  AuthenticatedAdminTarifsRouteImport.update({
    id: '/tarifs',
    path: '/tarifs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTemoignagesRoute =
  AuthenticatedAdminTemoignagesRouteImport.update({
    id: '/temoignages',
    path: '/temoignages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTextesRoute =
  AuthenticatedAdminTextesRouteImport.update({
    id: '/textes',
    path: '/textes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/realisations': typeof RealisationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/atouts': typeof AuthenticatedAdminAtoutsRoute
  '/admin/comparaison': typeof AuthenticatedAdminComparaisonRoute
  '/admin/etapes': typeof AuthenticatedAdminEtapesRoute
  '/admin/faq': typeof AuthenticatedAdminFaqRoute
  '/admin/medias': typeof AuthenticatedAdminMediasRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/realisations': typeof AuthenticatedAdminRealisationsRoute
  '/admin/sections': typeof AuthenticatedAdminSectionsRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/tarifs': typeof AuthenticatedAdminTarifsRoute
  '/admin/temoignages': typeof AuthenticatedAdminTemoignagesRoute
  '/admin/textes': typeof AuthenticatedAdminTextesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/realisations': typeof RealisationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/admin/atouts': typeof AuthenticatedAdminAtoutsRoute
  '/admin/comparaison': typeof AuthenticatedAdminComparaisonRoute
  '/admin/etapes': typeof AuthenticatedAdminEtapesRoute
  '/admin/faq': typeof AuthenticatedAdminFaqRoute
  '/admin/medias': typeof AuthenticatedAdminMediasRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/realisations': typeof AuthenticatedAdminRealisationsRoute
  '/admin/sections': typeof AuthenticatedAdminSectionsRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/tarifs': typeof AuthenticatedAdminTarifsRoute
  '/admin/temoignages': typeof AuthenticatedAdminTemoignagesRoute
  '/admin/textes': typeof AuthenticatedAdminTextesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/realisations': typeof RealisationsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admin/atouts': typeof AuthenticatedAdminAtoutsRoute
  '/_authenticated/admin/comparaison': typeof AuthenticatedAdminComparaisonRoute
  '/_authenticated/admin/etapes': typeof AuthenticatedAdminEtapesRoute
  '/_authenticated/admin/faq': typeof AuthenticatedAdminFaqRoute
  '/_authenticated/admin/medias': typeof AuthenticatedAdminMediasRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/realisations': typeof AuthenticatedAdminRealisationsRoute
  '/_authenticated/admin/sections': typeof AuthenticatedAdminSectionsRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/tarifs': typeof AuthenticatedAdminTarifsRoute
  '/_authenticated/admin/temoignages': typeof AuthenticatedAdminTemoignagesRoute
  '/_authenticated/admin/textes': typeof AuthenticatedAdminTextesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/realisations'
    | '/reset-password'
    | '/services'
    | '/admin'
    | '/admin/atouts'
    | '/admin/comparaison'
    | '/admin/etapes'
    | '/admin/faq'
    | '/admin/medias'
    | '/admin/messages'
    | '/admin/realisations'
    | '/admin/sections'
    | '/admin/services'
    | '/admin/tarifs'
    | '/admin/temoignages'
    | '/admin/textes'
    | '/admin/'
    | '/api/public/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/realisations'
    | '/reset-password'
    | '/services'
    | '/admin/atouts'
    | '/admin/comparaison'
    | '/admin/etapes'
    | '/admin/faq'
    | '/admin/medias'
    | '/admin/messages'
    | '/admin/realisations'
    | '/admin/sections'
    | '/admin/services'
    | '/admin/tarifs'
    | '/admin/temoignages'
    | '/admin/textes'
    | '/admin'
    | '/api/public/media/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/realisations'
    | '/reset-password'
    | '/services'
    | '/_authenticated/admin'
    | '/_authenticated/admin/atouts'
    | '/_authenticated/admin/comparaison'
    | '/_authenticated/admin/etapes'
    | '/_authenticated/admin/faq'
    | '/_authenticated/admin/medias'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/realisations'
    | '/_authenticated/admin/sections'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/tarifs'
    | '/_authenticated/admin/temoignages'
    | '/_authenticated/admin/textes'
    | '/_authenticated/admin/'
    | '/api/public/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RealisationsRoute: typeof RealisationsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realisations': {
      id: '/realisations'
      path: '/realisations'
      fullPath: '/realisations'
      preLoaderRoute: typeof RealisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/atouts': {
      id: '/_authenticated/admin/atouts'
      path: '/atouts'
      fullPath: '/admin/atouts'
      preLoaderRoute: typeof AuthenticatedAdminAtoutsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/comparaison': {
      id: '/_authenticated/admin/comparaison'
      path: '/comparaison'
      fullPath: '/admin/comparaison'
      preLoaderRoute: typeof AuthenticatedAdminComparaisonRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/etapes': {
      id: '/_authenticated/admin/etapes'
      path: '/etapes'
      fullPath: '/admin/etapes'
      preLoaderRoute: typeof AuthenticatedAdminEtapesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/faq': {
      id: '/_authenticated/admin/faq'
      path: '/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AuthenticatedAdminFaqRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/medias': {
      id: '/_authenticated/admin/medias'
      path: '/medias'
      fullPath: '/admin/medias'
      preLoaderRoute: typeof AuthenticatedAdminMediasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/realisations': {
      id: '/_authenticated/admin/realisations'
      path: '/realisations'
      fullPath: '/admin/realisations'
      preLoaderRoute: typeof AuthenticatedAdminRealisationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sections': {
      id: '/_authenticated/admin/sections'
      path: '/sections'
      fullPath: '/admin/sections'
      preLoaderRoute: typeof AuthenticatedAdminSectionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tarifs': {
      id: '/_authenticated/admin/tarifs'
      path: '/tarifs'
      fullPath: '/admin/tarifs'
      preLoaderRoute: typeof AuthenticatedAdminTarifsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/temoignages': {
      id: '/_authenticated/admin/temoignages'
      path: '/temoignages'
      fullPath: '/admin/temoignages'
      preLoaderRoute: typeof AuthenticatedAdminTemoignagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/textes': {
      id: '/_authenticated/admin/textes'
      path: '/textes'
      fullPath: '/admin/textes'
      preLoaderRoute: typeof AuthenticatedAdminTextesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAtoutsRoute: typeof AuthenticatedAdminAtoutsRoute
  AuthenticatedAdminComparaisonRoute: typeof AuthenticatedAdminComparaisonRoute
  AuthenticatedAdminEtapesRoute: typeof AuthenticatedAdminEtapesRoute
  AuthenticatedAdminFaqRoute: typeof AuthenticatedAdminFaqRoute
  AuthenticatedAdminMediasRoute: typeof AuthenticatedAdminMediasRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminRealisationsRoute: typeof AuthenticatedAdminRealisationsRoute
  AuthenticatedAdminSectionsRoute: typeof AuthenticatedAdminSectionsRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminTarifsRoute: typeof AuthenticatedAdminTarifsRoute
  AuthenticatedAdminTemoignagesRoute: typeof AuthenticatedAdminTemoignagesRoute
  AuthenticatedAdminTextesRoute: typeof AuthenticatedAdminTextesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAtoutsRoute: AuthenticatedAdminAtoutsRoute,
  AuthenticatedAdminComparaisonRoute: AuthenticatedAdminComparaisonRoute,
  AuthenticatedAdminEtapesRoute: AuthenticatedAdminEtapesRoute,
  AuthenticatedAdminFaqRoute: AuthenticatedAdminFaqRoute,
  AuthenticatedAdminMediasRoute: AuthenticatedAdminMediasRoute,
  AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
  AuthenticatedAdminRealisationsRoute: AuthenticatedAdminRealisationsRoute,
  AuthenticatedAdminSectionsRoute: AuthenticatedAdminSectionsRoute,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
  AuthenticatedAdminTarifsRoute: AuthenticatedAdminTarifsRoute,
  AuthenticatedAdminTemoignagesRoute: AuthenticatedAdminTemoignagesRoute,
  AuthenticatedAdminTextesRoute: AuthenticatedAdminTextesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RealisationsRoute: RealisationsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
