/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CreerMonSiteRouteImport } from './routes/creer-mon-site'
import { Route as ModelesRouteImport } from './routes/modeles'
import { Route as RealisationsRouteImport } from './routes/realisations'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ApercuProjectIdRouteImport } from './routes/apercu.$projectId'
import { Route as ModelesTemplateIdRouteImport } from './routes/modeles.$templateId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CreerMonSiteRoute = CreerMonSiteRouteImport.update({
  id: '/creer-mon-site',
  path: '/creer-mon-site',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelesRoute = ModelesRouteImport.update({
  id: '/modeles',
  path: '/modeles',
  getParentRoute: () => rootRouteImport,
} as any)
const RealisationsRoute = RealisationsRouteImport.update({
  id: '/realisations',
  path: '/realisations',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ApercuProjectIdRoute = ApercuProjectIdRouteImport.update({
  id: '/apercu/$projectId',
  path: '/apercu/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelesTemplateIdRoute = ModelesTemplateIdRouteImport.update({
  id: '/$templateId',
  path: '/$templateId',
  getParentRoute: () => ModelesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/creer-mon-site': typeof CreerMonSiteRoute
  '/modeles': typeof ModelesRouteWithChildren
  '/realisations': typeof RealisationsRoute
  '/services': typeof ServicesRoute
  '/apercu/$projectId': typeof ApercuProjectIdRoute
  '/modeles/$templateId': typeof ModelesTemplateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/creer-mon-site': typeof CreerMonSiteRoute
  '/modeles': typeof ModelesRouteWithChildren
  '/realisations': typeof RealisationsRoute
  '/services': typeof ServicesRoute
  '/apercu/$projectId': typeof ApercuProjectIdRoute
  '/modeles/$templateId': typeof ModelesTemplateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/creer-mon-site': typeof CreerMonSiteRoute
  '/modeles': typeof ModelesRouteWithChildren
  '/realisations': typeof RealisationsRoute
  '/services': typeof ServicesRoute
  '/apercu/$projectId': typeof ApercuProjectIdRoute
  '/modeles/$templateId': typeof ModelesTemplateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/creer-mon-site'
    | '/modeles'
    | '/realisations'
    | '/services'
    | '/apercu/$projectId'
    | '/modeles/$templateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/creer-mon-site'
    | '/modeles'
    | '/realisations'
    | '/services'
    | '/apercu/$projectId'
    | '/modeles/$templateId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/creer-mon-site'
    | '/modeles'
    | '/realisations'
    | '/services'
    | '/apercu/$projectId'
    | '/modeles/$templateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CreerMonSiteRoute: typeof CreerMonSiteRoute
  ModelesRoute: typeof ModelesRouteWithChildren
  RealisationsRoute: typeof RealisationsRoute
  ServicesRoute: typeof ServicesRoute
  ApercuProjectIdRoute: typeof ApercuProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creer-mon-site': {
      id: '/creer-mon-site'
      path: '/creer-mon-site'
      fullPath: '/creer-mon-site'
      preLoaderRoute: typeof CreerMonSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modeles': {
      id: '/modeles'
      path: '/modeles'
      fullPath: '/modeles'
      preLoaderRoute: typeof ModelesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realisations': {
      id: '/realisations'
      path: '/realisations'
      fullPath: '/realisations'
      preLoaderRoute: typeof RealisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apercu/$projectId': {
      id: '/apercu/$projectId'
      path: '/apercu/$projectId'
      fullPath: '/apercu/$projectId'
      preLoaderRoute: typeof ApercuProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modeles/$templateId': {
      id: '/modeles/$templateId'
      path: '/$templateId'
      fullPath: '/modeles/$templateId'
      preLoaderRoute: typeof ModelesTemplateIdRouteImport
      parentRoute: typeof ModelesRoute
    }
  }
}

interface ModelesRouteChildren {
  ModelesTemplateIdRoute: typeof ModelesTemplateIdRoute
}

const ModelesRouteChildren: ModelesRouteChildren = {
  ModelesTemplateIdRoute: ModelesTemplateIdRoute,
}

const ModelesRouteWithChildren =
  ModelesRoute._addFileChildren(ModelesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CreerMonSiteRoute: CreerMonSiteRoute,
  ModelesRoute: ModelesRouteWithChildren,
  RealisationsRoute: RealisationsRoute,
  ServicesRoute: ServicesRoute,
  ApercuProjectIdRoute: ApercuProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
